site_name: PyDjinni
copyright: Copyright &copy; 2024 jothepro
theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Open Sans
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: blue
      scheme: default
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
plugins:
  - tags
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md